# Generated by Django 2.2.6 on 2019-11-05 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quser', '0004_quser_identity'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=64)),
                ('address', models.TextField()),
                ('postcode', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
                ('state', models.IntegerField()),
            ],
        ),
    ]
