# Generated by Django 2.2.6 on 2019-11-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0003_order_info_pay_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycar',
            name='goods_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
