# Generated by Django 2.2.6 on 2019-10-31 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quser', '0004_quser_identity'),
        ('Shop', '0004_auto_20191030_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Quser.Quser'),
            preserve_default=False,
        ),
    ]
