# Generated by Django 2.2.6 on 2019-10-30 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_auto_20191030_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shop.GoodsType'),
        ),
    ]
