# Generated by Django 2.2.6 on 2019-11-05 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quser', '0006_auto_20191105_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsaddress',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Quser.Quser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodsaddress',
            name='address',
            field=models.TextField(),
        ),
    ]
